% Generated on Fri Oct  5 09:31:59 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: fsk\_modem}\\
        \hline
        \rowcolor{blue}
            Container                                   & OCPI Platform & OCPI Target & Tool   & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_1rx\_1tx\_thruasm\_mode\_2\_cmos\_e3xx & e3xx          & zynq        & Vivado & 2017.1  & xc7z020clg484-1 & 27093           & 23559      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 148 \\ BUFGCTRL: 2 \\ RAMB36E1: 34 \\ ODDR: 8 \\ RAMB18E1: 2 \\ BUFG: 2\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
