% Generated on Fri Oct  5 09:31:58 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: empty}\\
        \hline
        \rowcolor{blue}
            Container                                     & OCPI Platform & OCPI Target & Tool   & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base                                          & e3xx          & zynq        & Vivado & 2017.1  & xc7z020clg484-1 & 2045            & 1996       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ RAMB36E1: 2 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_bypassasm\_mode\_2\_cmos\_e3xx & e3xx          & zynq        & Vivado & 2017.1  & xc7z020clg484-1 & 2045            & 1996       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ RAMB36E1: 2 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_1rx\_0tx\_bypassasm\_mode\_2\_cmos\_e3xx & e3xx          & zynq        & Vivado & 2017.1  & xc7z020clg484-1 & 2045            & 1996       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ RAMB36E1: 2 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_1rx\_1tx\_bypassasm\_mode\_2\_cmos\_e3xx & e3xx          & zynq        & Vivado & 2017.1  & xc7z020clg484-1 & 2045            & 1996       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ RAMB36E1: 2 \\ BUFG: 1\end{tabular} \\
            \hline
            cnt\_e3xx\_mimo\_xcvr\_filter                 & e3xx          & zynq        & Vivado & 2017.1  & xc7z020clg484-1 & 2045            & 1996       & 100.0            & \begin{tabular}{@{}l@{}}BUFGCTRL: 1 \\ RAMB36E1: 2 \\ BUFG: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
