# This is the Makefile for worker e3xx_rx.rcc
RccIncludeDirs+=$(OCPI_PREREQUISITES_DIR)/ad9361/include/ # for ad9361.h
RccIncludeDirs+=./include
RccIncludeDirs+=./include/ad9361/
RccOnlyPlatforms=xilinx13_4
include $(OCPI_CDK_DIR)/include/worker.mk
