# This is the hdl/cards library

# All workers created here in *.<model> will be built automatically
# All tests created here in *.test directories will be built/run automatically
# To limit the workers that actually get built, set the Workers= variable
# To limit the tests that actually get built/run, set the Tests= variable

Workers=\
        ad5662.hdl \
        ad5662_em.hdl \
        e3xx_i2c.hdl \
        e3xx_mimo_xcvr_filter.hdl \
        e3xx_mimo_xcvr_filter_proxy.rcc \
        e3xx_rx.rcc \
        e3xx_tx.rcc \

include $(OCPI_CDK_DIR)/include/library.mk
