% Generated on Tue Apr 30 11:53:57 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly "dc\_offset\_iq\_imbalance\_mixer\_cic\_dec\_rp\_cordic\_fir\_real"}\\
        \hline
        \rowcolor{blue}
            Container                                   & OCPI Platform & OCPI Target & Tool   & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_mode\_2\_cmos\_e3xx & e3xx          & zynq        & Vivado & 2017.1  & xc7z020clg484-1 & 16969           & 16107      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 82 \\ ODDR: 1 \\ BUFGCTRL: 2 \\ BUFG: 2 \\ RAMB36E1: 18 \\ RAMB18E1: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
