# This is the Makefile for the test directory which tests component "e3xx_mimo_xcvr_filter_proxy"
include $(OCPI_CDK_DIR)/include/application.mk

all:
	make -C assemblies

clean::
	make -C assemblies clean
