% Generated on Fri Oct  5 09:31:54 2018

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly: dc\_offset\_iq\_imbalance\_mixer\_cic\_dec\_timestamper}\\
        \hline
        \rowcolor{blue}
            Container                                   & OCPI Platform & OCPI Target & Tool   & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_mode\_2\_cmos\_e3xx & e3xx          & zynq        & Vivado & 2017.1  & xc7z020clg484-1 & 9571            & 9370       & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 15 \\ BUFGCTRL: 2 \\ RAMB36E1: 18 \\ ODDR: 1 \\ RAMB18E1: 1 \\ BUFG: 2\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
