% Generated on Tue Apr 30 11:53:57 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly "ad9361\_1r1t\_test\_adc\_asm"}\\
        \hline
        \rowcolor{blue}
            Container                                   & OCPI Platform & OCPI Target & Tool   & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_1rx\_0tx\_thruasm\_mode\_2\_cmos\_e3xx & e3xx          & zynq        & Vivado & 2017.1  & xc7z020clg484-1 & 6505            & 13019      & 100.0            & \begin{tabular}{@{}l@{}}ODDR: 1 \\ BUFGCTRL: 2 \\ BUFG: 2 \\ RAMB36E1: 18 \\ RAMB18E1: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
