% Generated on Tue Apr 30 11:53:57 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly "mfsk2\_zp16\_fir\_real\_phase\_to\_amp\_cordic\_cic\_int"}\\
        \hline
        \rowcolor{blue}
            Container                                   & OCPI Platform & OCPI Target & Tool   & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            base                                        & e3xx          & zynq        & Vivado & 2017.1  & xc7z020clg484-1 & 15764           & 12512      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 66 \\ BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 34\end{tabular} \\
            \hline
            cnt\_0rx\_1tx\_thruasm\_mode\_2\_cmos\_e3xx & e3xx          & zynq        & Vivado & 2017.1  & xc7z020clg484-1 & 15764           & 12512      & 100.0            & \begin{tabular}{@{}l@{}}DSP48E1: 66 \\ BUFGCTRL: 1 \\ BUFG: 1 \\ RAMB36E1: 34\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
