# This is the hdl/devices library

# All workers created here in *.<model> will be built automatically
# All tests created here in *.test directories will be built/run automatically
# To limit the workers that actually get built, set the Workers= variable
# To limit the tests that actually get built/run, set the Tests= variable
Workers=

include $(OCPI_CDK_DIR)/include/library.mk
