% Generated on Tue Apr 30 11:53:57 2019

% It is best to wrap this table in \begin{landscape} and \end{landscape} in its including doc
\begin{tiny}
    \begin{longtable}[l]{* {10}{|c}|}
    \captionsetup{justification=raggedright,singlelinecheck=false}
    \caption{Resource Utilization Table for hdl-assembly "data\_src\_to\_dac"}\\
        \hline
        \rowcolor{blue}
            Container                                 & OCPI Platform & OCPI Target & Tool   & Version & Device          & Registers (Typ) & LUTs (Typ) & Fmax (MHz) (Typ) & Memory/Special Functions \\
            \hline
            cnt\_0rx\_1tx\_txsrc\_mode\_2\_cmos\_e3xx & e3xx          & zynq        & Vivado & 2017.1  & xc7z020clg484-1 & 3474            & 3386       & 100.0            & \begin{tabular}{@{}l@{}}ODDR: 8 \\ BUFGCTRL: 2 \\ BUFG: 2 \\ RAMB36E1: 2 \\ RAMB18E1: 1\end{tabular} \\
            \hline
        \end{longtable}
\end{tiny}
